
# Configuration file for backupd.

# Absolute path: source directory.
SOURCE=/home/ars/SPbU/Linux.ThirdSem/source

# Absolute path: target directory.
#  Will be created if does not exist.
TARGET=/home/ars/SPbU/Linux.ThirdSem/target

# Backup frequency.
FREQUENCY=1min
